CREATE TABLE ECOLES (
  idEcole INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nomEcole VARCHAR(255),
  adresse1 VARCHAR(255) ,
  adresse2 VARCHAR(255) ,
  code_Postal INT  ,
  ville VARCHAR(255) ,
  nom_Directeur VARCHAR(255) ,
  nom_Repsonsable VARCHAR(255) ,
  num_telephone INT  ,
  num_fax INT
  
);


CREATE TABLE CLASSES (
  idClasses INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ECOLES_idEcole INT NOT NULL ,
  Nb_Creches INT  ,
  Nb_Maternelles INT  ,
  Nb_Colleges INT  ,
  Nb_Lycees INT  ,
  FOREIGN KEY(ECOLES_idEcole) REFERENCES ECOLES(idEcole)
);



CREATE TABLE ELEVES (
  idELEVES INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ECOLES_idEcole INT   NOT NULL,
  CLASSES_idClasses INT   NOT NULL,
  Nb_Creches INT  ,
  Nb_Primaires INT  ,
  Nb_Colleges INT  ,
  Nb_Lycees INT,
  CONSTRAINT FK_ELEVES_ECOLE FOREIGN KEY (ECOLES_idEcole) REFERENCES ECOLES(idEcole),
  CONSTRAINT FK_ELEVES_CLASSES FOREIGN KEY (CLASSES_idClasses) REFERENCES CLASSES(idClasses)
);


CREATE TABLE RDV (
  idRDV INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ECOLES_idEcole INT   NOT NULL,
  commercial VARCHAR(255) ,
  CONSTRAINT FK_RDV_ECOLE FOREIGN KEY (ECOLES_idEcole) REFERENCES ECOLES(idEcole)
);


